# Generated by Django 2.2 on 2019-04-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postread'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postread',
            options={},
        ),
    ]
