# Generated by Django 2.2 on 2019-04-20 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20190420_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='postread',
            name='who_read',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rel_readers', to=settings.AUTH_USER_MODEL, verbose_name='Читатель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postread',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_authors', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
