# Generated by Django 2.2 on 2019-04-20 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190420_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postread',
            name='author',
        ),
        migrations.AlterField(
            model_name='postread',
            name='who_read',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readers', to=settings.AUTH_USER_MODEL, verbose_name='Читатель'),
        ),
    ]
